# Generated by Django 4.2.29 on 2026-04-13 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='试卷说明')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='考试时长(分钟)')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('pass_score', models.IntegerField(default=60, verbose_name='及格分数')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='题号')),
                ('question_type', models.CharField(choices=[('single', '单选'), ('multi', '多选')], default='single', max_length=10, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题干')),
                ('score', models.IntegerField(default=5, verbose_name='分值')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='所属试卷')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='选项标签')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, verbose_name='作答记录')),
                ('total_score', models.IntegerField(default=0, verbose_name='得分')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='已交卷')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exams.exam', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='AnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list, verbose_name='选择的选项')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('earned_score', models.IntegerField(default=0, verbose_name='得分')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='题目')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exams.examrecord', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '答题详情',
                'verbose_name_plural': '答题详情',
            },
        ),
    ]
